use std::error::Error;

pub fn run(input: &str) -> Result<Vec<&str>, Box<dyn Error>> {
    let mut outputs = Vec::new();
    println!("Input: {input}");

    Ok(outputs)
}
